### ISSUE TITLE
can not setup normally

### ISSUE THREAD

**Issue by Jacky486** [Rachel030219/Poweramp-LRC-Plugin#11]
Open poweramp can not setup , touch the application to setup. The notification can be seen but still setup failed.

**Comment by Rachel030219** [comment]
**PLEASE** follow the instructions and use a template to open an issue. Describing it in ambiguous language without any information needed to locate the problem provides no help, and will cause your issue getting closed.
**请务必** 跟随指引并使用模板来提出 issue 。使用模糊的语言描述且不包含任何定位问题所需的信息 issue 不会提供任何帮助，并且会使您的 issue 被关闭。**您可以使用中文。**
