### ISSUE TITLE
[BUG]l三星点击通知显示歌词时 会出现停止运行 安卓q 

### ISSUE THREAD

**Issue by aperport** [Rachel030219/Poweramp-LRC-Plugin#12]
**Describe the bug**

**To Reproduce**

**Device info:**
 - Device: [e.g. Pixel XL]
 - Android version: [e.g. MIUI 10(Oreo)]
 - Version: [e.g. 22]

**Additional context**

**Comment by Rachel030219** [comment]
新版已在 Play Store 发布，若仍报错，请将错误日志贴于此 issue 下。感谢。

**Comment by aperport** [comment]
> 新版已在Play商店发布，若仍报错，替换错误日志贴于此期下。感谢。

[20200405-125900.log](https://github.com/Rachel030219/Poweramp-LRC-Plugin/files/4432975/20200405-125900.log)
[20200405-125916.log](https://github.com/Rachel030219/Poweramp-LRC-Plugin/files/4432976/20200405-125916.log)
这样是错误日志吧？ 现在不闪退 出了这个文件夹 希望有时间解决 我挺期待这个插件的

**Comment by Rachel030219** [comment]
多谢，请问能否提供原文件的实际目录与文件名（直接文件管理器截图，出现原曲与歌词文件即可）？

**Comment by aperport** [comment]
> 多谢，请问能否提供原文件的实际目录与文件名（直接文件管理器截图，出现原曲与歌词文件即可）？

![Screenshot_20200405-145134_My Files](https://user-images.githubusercontent.com/63085096/78468761-5b874400-774d-11ea-82da-70529e11df12.jpg)
这样吗？

**Comment by Rachel030219** [comment]
是的，感谢
这个问题将尽可能快地得到解决

**Comment by aperport** [comment]
> 是的，感谢
> 这个问题将尽快快地得到解决

更新1.2后好像还是这样

**Comment by Rachel030219** [comment]
@aperport 请问是仍然报错吗？能否提供错误日志（如果所报错误不同）？

**Comment by aperport** [comment]
> @aperport请问是仍然报错吗？能否提供错误日志（如果所报错误不同）？

我感觉错误相同 不过还是给日志吧
[20200408-084349.log](https://github.com/Rachel030219/Poweramp-LRC-Plugin/files/4447619/20200408-084349.log)

**Comment by Rachel030219** [comment]
@aperport 请问是否已正确按照通知栏提示指定歌曲与歌词所在路径？看起来似乎好像很诡异…日志显示没有读写权限，也没有授权对任何文件夹的访问，然而在 Android 10 上应该会弹出通知请求对指定路径下文件的读取权限…

**Comment by aperport** [comment]
> @aperport请问是否已正确正确按照通知栏提示指定歌曲与歌词所在路径？看起来好像很诡异…日志显示没有读写权限，也没有授权对任何文件夹的访问，而在Android 10上应该会弹出通知请求对指定路径下文件的读取权限...

对的 他确实不要一点权限 我也很纳闷他怎么du qu读取歌词
[Screenshot_20200413-083604_Permission controller.jpg.pdf](https://github.com/Rachel030219/Poweramp-LRC-Plugin/files/4467475/Screenshot_20200413-083604_Permission.controller.jpg.pdf)

**Comment by aperport** [comment]
> @aperport 请问是否已正确按照通知栏提示指定歌曲与歌词所在路径？看起来似乎好像很诡异…日志显示没有读写权限，也没有授权对任何文件夹的访问，然而在 Android 10 上应该会弹出通知请求对指定路径下文件的读取权限…

我用别的手机试了试 确实是在三星上没有申请任何权限 我也没办法给予它存储权限

**Comment by Rachel030219** [comment]
@aperport 唔，无法申请/授予读写权限是 Android 10 以上的特性，以「存储访问框架 (SAF)」提供的 API ，通过打开文件管理器并授权的方式取得对目录下所有文件的访问权限。正常情况下，在 Android 10 及以上的系统中，应用应当会弹出一个通知，申请对应目录的访问权限。如果没有，那说明要么是系统拦截了通知，要么就是其他系统做的东西影响了正常的行为…或许检查一下通知是否被拦截？

**Comment by aperport** [comment]
应该就是被系统影响的 我在设置里看到这个软件不需要任何权限 ------------------ 原始邮件 ------------------
发件人: "Rachel Tang"<notifications@github.com>
发送时间: 2020年5月4日(星期一) 晚上6:14
收件人: "Rachel030219/Poweramp-LRC-Plugin"<Poweramp-LRC-Plugin@noreply.github.com>;
抄送: "aperport"<1774844076@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [Rachel030219/Poweramp-LRC-Plugin] [BUG]l三星点击通知显示歌词时 会出现停止运行 安卓q  (#12)




 
@aperport 唔，无法申请/授予读写权限是 Android 10 以上的特性，以「存储访问框架 (SAF)」提供的 API ，通过打开文&#x4EF6;管理器并授权的方式取得对目录下所有文&#x4EF6;的访问权限。正常情况下，在 Android 10 及以上的系统中，应用应当会弹出一个通知，申请对应目录的访问权限。如果没有，那说明要么是系统拦截了通知，要么就是其他系统做的东西影响了正常的行为…或许检查一下通知是否被拦截？
 
&mdash;

**Comment by Rachel030219** [comment]
您好，请问能否使用 1.3 PREVIEW 版本的反馈日志功能，抓取错误日志并将其贴在此处，以帮助定位问题？感谢

**Comment by aperport** [comment]
谢谢 更新后索要存储权限 可以用了 顺便 高考加油 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Rachel&amp;nbsp;Tang&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月3日(星期三) 中午12:35
收件人:&nbsp;&quot;Rachel030219/Poweramp-LRC-Plugin&quot;<Poweramp-LRC-Plugin@noreply.github.com&gt;;
抄送:&nbsp;&quot;aperport&quot;<1774844076@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Rachel030219/Poweramp-LRC-Plugin] [BUG]l三星点击通知显示歌词时 会出现停止运行 安卓q  (#12)
