### ISSUE TITLE
[BUG]lrc歌词类似卡拉OK的效果分辨不出来

### ISSUE THREAD

**Issue by Dcdcdc1993** [Rachel030219/Poweramp-LRC-Plugin#13]
![Screenshot_20200404-230940_Poweramp](https://user-images.githubusercontent.com/63157493/78454262-8def5d80-76c9-11ea-8e5c-430273d2dfc5.png)

**Comment by Rachel030219** [comment]
感谢反馈，由于这并非标准的 LRC 格式，目前阶段暂不准备支持。
