### ISSUE TITLE
log 错误日志 小米10p miui11.16

### ISSUE THREAD

**Issue by dyboxoo** [Rachel030219/Poweramp-LRC-Plugin#14]
************ CAUSE OF ERROR ************

java.lang.RuntimeException: Unable to start service net.rachel030219.poweramplrc.LrcService@b6fdd8f with Intent { cmp=net.rachel030219.poweramplrc/.LrcService (has extras) }: java.lang.SecurityException: Document primary:轻应用系列/轻音乐/Download/暗号 - 周杰伦.lrc is not a descendant of downloads
android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4149)
android.app.ActivityThread.access$1900(ActivityThread.java:225)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1922)
android.os.Handler.dispatchMessage(Handler.java:107)
android.os.Looper.loop(Looper.java:227)
android.app.ActivityThread.main(ActivityThread.java:7544)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)

************ PATHS ************

key: primary, value: content://com.android.providers.downloads.documents/tree/downloads/document/

************ DEVICE INFORMATION ************

Brand: Xiaomi
Device: cmi
Model: Mi 10 Pro
Id: QKQ1.191117.002

**Comment by Rachel030219** [comment]
您好，抱歉回复过晚，请问现在是否仍然存在类似问题？

**Comment by dyboxoo** [comment]
没了。是我没下载本地歌词。希望增加锁定按钮谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rachel Tang"<notifications@github.com&gt;; 
发送时间: 2020年5月4日(星期一) 晚上10:24
收件人: "Rachel030219/Poweramp-LRC-Plugin"<Poweramp-LRC-Plugin@noreply.github.com&gt;; 
抄送: "dybbs"<dybbs@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Rachel030219/Poweramp-LRC-Plugin] log 错误日志 小米10p miui11.16 (#14)





 
您好，抱歉回复过晚，请问现在是否仍然存在类似问题？

**Comment by Rachel030219** [comment]
@dyboxoo 收到，锁定功能将在未来几个版本内尝试加入
