### ISSUE TITLE
Is this app work in android 10 [REQUEST]

### ISSUE THREAD

**Issue by rubbesh** [Rachel030219/Poweramp-LRC-Plugin#19]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Rachel030219** [comment]
Yes.

**Comment by rubbesh** [comment]
But showing not allowed to draw over other apps why?

**Comment by rubbesh** [comment]
Please reply..

**Comment by Rachel030219** [comment]
> But showing not allowed to draw over other apps why?

@rubbesh Never report bugs as feature requests or without your device and things you did. Follow the instructions in the app and it should work fine flawlessly.
