### ISSUE TITLE
無法讀取 UTF-16 的歌詞檔

### ISSUE THREAD

**Issue by HatsuneMiku831** [Rachel030219/Poweramp-LRC-Plugin#20]
手機使用的是Android 10
已有給App權限，但是還是無法讀取

**Comment by Rachel030219** [comment]
请问能否提供应用内设置生成的 log 以协助定位问题？

**Comment by HatsuneMiku831** [comment]
好的，稍等一下

**Comment by HatsuneMiku831** [comment]
[20200813-230729.txt](https://github.com/Rachel030219/Poweramp-LRC-Plugin/files/5069828/20200813-230729.txt)

**Comment by HatsuneMiku831** [comment]
!!! 我自己找到問題了 開啟到開發人員選項裡的"強制允許將應用程式寫入外部儲存空間"

**Comment by Rachel030219** [comment]
> !!! 我自己找到問題了 開啟到開發人員選項裡的"強制允許將應用程式寫入外部儲存空間"

唔…请问问题是否已得到解决？

**Comment by HatsuneMiku831** [comment]
我錯了結果沒有 OAO

**Comment by HatsuneMiku831** [comment]
有些正常，有些不正常

**Comment by Rachel030219** [comment]
> 有些正常，有些不正常

啊…请问能否提供正常与不正常两种情况下的 log ？
如果可以，能否附上对应的 lrc 文件？

**Comment by HatsuneMiku831** [comment]
[ 非正常.txt](https://github.com/Rachel030219/Poweramp-LRC-Plugin/files/5069917/default.txt)
[正常.txt](https://github.com/Rachel030219/Poweramp-LRC-Plugin/files/5069918/default.txt)

**Comment by HatsuneMiku831** [comment]
剛比對了一下，好像是歌曲名稱問題

**Comment by HatsuneMiku831** [comment]
非正常的裡面多了個.mp3，但是歌詞檔無後面有多加.mp3

**Comment by Rachel030219** [comment]
> 非正常的裡面多了個.mp3，但是歌詞檔無後面有多加.mp3

意思是说…扩展名前面的部分不一致吗？
是否已统一为 XXX.mp3 （或其它格式）对应 XXX.lrc ？若非，麻烦统一后重试，多谢

**Comment by HatsuneMiku831** [comment]
正在嘗試中~

**Comment by HatsuneMiku831** [comment]
還是不能

**Comment by HatsuneMiku831** [comment]
[導入.zip](https://github.com/Rachel030219/Poweramp-LRC-Plugin/files/5069987/default.zip)

**Comment by HatsuneMiku831** [comment]
裡面有音檔跟歌詞檔

**Comment by Rachel030219** [comment]
您好，文件已经收到了，初步推测是编码问题…
我这边一开始也无法识别，用文本编辑器打开发现编码是 `UTF-16LE` ，将其以 `UTF-8` 保存后一切正常。
我将尽量快地解决这个问题。在此期间（保守估计至少六天以后，如果拖延症再犯可能更长），若您有需要，可将文件转码为 `UTF-8` 。

**Comment by HatsuneMiku831** [comment]
好的 OuO

**Comment by Rachel030219** [comment]
您好，
经过初步排查，这个问题暂时难以得到解决（无法以通常方式获取文件编码），原因未知，烦请使用其它文件编码（例如 `BIG-5` 或是 `UTF-8`）…十分抱歉

**Comment by fei0316** [comment]
剛剛測試了一下，勾選自動偵測編碼就能使用了。可能這幾個月來的更新已經改善了編碼的偵測？
