### ISSUE TITLE
功能完善[REQUEST]

### ISSUE THREAD

**Issue by SplitGemini** [Rachel030219/Poweramp-LRC-Plugin#21]
**Is your feature request related to a problem? Please describe.**
浮动歌词误触

**Describe the solution you'd like**
能够点击穿透（锁定后忽略点击操作）

**Describe alternatives you've considered**
希望最终效果类似各大主流网络播放器（QQ音乐，网易云音乐等）的桌面歌词效果

**Additional context**
不知道开发者有没有浏览过 [APlayer](https://github.com/rRemix/APlayer) ，我觉得可以借鉴它的桌面歌词代码

**Comment by Rachel030219** [comment]
收到，这个功能已经进入待办列表，并将在未来版本推出

**Comment by SplitGemini** [comment]
[HPLyrics](https://github.com/zhangliangming/HPLyrics)

**Comment by SplitGemini** [comment]
## 关于提高歌词精确度的想法
PowerampAPI给的是精确度是秒的吧，那么可以自己构造一个计时器在每两秒之间

**Comment by Rachel030219** [comment]
> ## 关于提高歌词精确度的想法
> PowerampAPI给的是精确度是秒的吧，那么可以自己构造一个计时器在每两秒之间

感谢提醒，这个方法我们也在考虑，或将在接下来的版本中推出。

**Comment by Rachel030219** [comment]
这个特性已经在最新版本实现。

> ## 关于提高歌词精确度的想法
> PowerampAPI给的是精确度是秒的吧，那么可以自己构造一个计时器在每两秒之间
