### ISSUE TITLE
[BUG] Plugin crashes

### ISSUE THREAD

**Issue by white-miku** [Rachel030219/Poweramp-LRC-Plugin#22]
**Describe the bug**
The plug-in crashes when starting playing a song

**To Reproduce**
1. Start playing music that have a .lrc file
2. Toast message is being shown says that 
plug-in was crashed and log file was saved
**Device info:**
 - Device: Xiaomi Mi6
 - Android version: LineageOS, Android 10

**Additional context**
Log, lrc and music files may be downloaded here: https://cloud.white-miku.me/s/Y6vsrZyGb1va2DQ

**Comment by Rachel030219** [comment]
Sorry for my late reply. Does the error still exist in the latest version?

**Comment by white-miku** [comment]
@Rachel030219 I'm sorry, I've forgot about the issue too. I can't check the plugin on the device I've mentioned in the issue, but on another device the plugin works normally.

**Comment by Rachel030219** [comment]
Then that's great!
