### ISSUE TITLE
[REQUEST] Lyrics window transparency

### ISSUE THREAD

**Issue by fei0316** [Rachel030219/Poweramp-LRC-Plugin#24]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like an option to choose the transparency of the lyrics box, instead of a fixed value like what we have right now. The option can be in the preferences page, next to the lyrics color option.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

Feel free to reply in Chinese if it's easier for you.

**Comment by Rachel030219** [comment]
Thanks for the issue and your understanding. This feature will be rolled out in the next few versions ;)
