### ISSUE TITLE
配置完成后无法运行，且打开自动关闭[BUG]

### ISSUE THREAD

**Issue by nekonanaya** [Rachel030219/Poweramp-LRC-Plugin#31]
LOG文件的内容：

************ DEVICE INFORMATION ************
Brand: vivo
Device: PD1986
Model: V1986A
Id: QP1A.190711.020
Product: PD1986

************ FIRMWARE ************
SDK Version: 29
Release: 10

************ PATHS ************

************ FOLDERS ************
name: Music, path: content://com.android.externalstorage.documents/tree/primary%3AMusic

************ CAUSE OF ERROR ************
com.mpatric.mp3agic.InvalidDataException: No mpegs frames found
com.mpatric.mp3agic.Mp3File.init(Mp3File.java:97)
com.mpatric.mp3agic.Mp3File.<init>(Mp3File.java:71)
com.mpatric.mp3agic.Mp3File.<init>(Mp3File.java:62)
net.rachel030219.poweramplrc.LrcWindow$readFile$2.invokeSuspend(LrcWindow.kt:236)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by fei0316** [comment]
這個問題已經解決了，但新版本還沒有推出。原因估計是你的音樂檔案不是mp3格式但打開了內嵌歌詞功能，而最新版本已經支援flac等其他格式。
