### ISSUE TITLE
[BUG]暂停时内部计时器没暂停

### ISSUE THREAD

**Issue by SplitGemini** [Rachel030219/Poweramp-LRC-Plugin#32]
**Describe the bug**
歌曲暂停时如果下一句歌词在一秒内歌词会上下来回跳

**To Reproduce**
1. 暂停播放
2. See error

**Device info:**
 - Device: 红米
 - Android version: MIUI 10(Oreo)
 - Version: 12.0.5

**Additional context**
大概是歌曲暂停没有暂停内部计时器

**Comment by Rachel030219** [comment]
您好，为我的工作疏忽致歉，这个问题已在最新版本修复。
