### ISSUE TITLE
[BUG] Lyrics outline not working properly with different font sizes

### ISSUE THREAD

**Issue by fei0316** [Rachel030219/Poweramp-LRC-Plugin#33]
**Describe the bug**
The outline for the lyrics do not seem to change when font size is changed. The outline seem to be staying at the original size.

**To Reproduce**
1. Turn on lyrics outline
2. Changed text and outline color (not sure if that matters)
3. Changed outline thickness and text size

**Device info:**
 - Device: OnePlus 7 Pro
 - Android version: Oxygen OS Android 10

Please see attached for the screenshot of error.
![Screenshot_20201116-002310__01](https://user-images.githubusercontent.com/8295915/99190648-a3ba1a80-27a2-11eb-915f-61f4a23a328d.jpg)

**Comment by Rachel030219** [comment]
Got that. It will be fixed ASAP.

**Comment by fei0316** [comment]
It's fixed now I think. Closing it. Thanks!
