### ISSUE TITLE
[BUG]下拉通知点开歌词后退出

### ISSUE THREAD

**Issue by nekonanaya** [Rachel030219/Poweramp-LRC-Plugin#40]
************ DEVICE INFORMATION ************
Brand: vivo
Device: PD1986
Model: V1986A
Id: QP1A.190711.020
Product: PD1986

************ FIRMWARE ************
SDK Version: 29
Release: 10
App Version:19

************ PATHS ************

************ FOLDERS ************
name: Music, path: content://com.android.externalstorage.documents/tree/primary%3AMusic

************ CAUSE OF ERROR ************
java.lang.RuntimeException: Unable to start service net.rachel030219.poweramplrc.LrcService@5af5bf4 with Intent { cmp=net.rachel030219.poweramplrc/.LrcService (has extras) }: java.lang.NumberFormatException: empty String
android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4422)
android.app.ActivityThread.access$2100(ActivityThread.java:255)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2138)
android.os.Handler.dispatchMessage(Handler.java:107)
android.os.Looper.loop(Looper.java:230)
android.app.ActivityThread.main(ActivityThread.java:7851)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

**Comment by Rachel030219** [comment]
感谢反馈！我将尽快着手分析这个问题。

**Comment by nekonanaya** [comment]
新版已解决~
