### ISSUE TITLE
[BUG?]安卓11 miui12.5  一直显示歌词不见了

### ISSUE THREAD

**Issue by ckx000** [Rachel030219/Poweramp-LRC-Plugin#44]
**Describe the bug**
lrc插件和poweramp都是最新的187和911版本
poweramp和lrc里都设置好了同样的媒体文件夹位置
通知栏处 lrc插件也能正确获取到当前播放的歌曲名。但是歌词悬浮框处一直显示“歌词不见了”
有过尝试播放没有同名lrc的音乐，插件设置后能出现是否手动加载一个歌词文件，然后手动指定文件后照样显示“歌词不见了”
无脑瞎猜是不是miui哪里拦截了插件读取lrc文件内容？

**To Reproduce**

**Device info:**
 - Device: K20P
 - Android version: MIUI 12.5（Android11）
 - Version: 11

**Comment by ckx000** [comment]
[20210914-012309.txt](https://github.com/Rachel030219/Poweramp-LRC-Plugin/files/7156382/20210914-012309.txt)
[20210913-232840.txt](https://github.com/Rachel030219/Poweramp-LRC-Plugin/files/7156383/20210913-232840.txt)
传2个导出的log。 时间早的那个是最新版试的
时间后的那个 是在poweramp里开了传统模式访问 并且找个1.5旧版的lrc插件测试的。
这个旧版提示就就有点不同了。 最新版提示 是切歌的时候 “歌词加载中”出现不超过0.2秒就提示歌词不见了。这个旧版在传统模式下是会出现1秒多加载中再显示歌词不见了。同时如果在插件设置里打开自动检测字符集后，就会提示歌词文件编码暂不支持。但是我用各种文本编辑器打开lrc文件都是正确显示文件编码是UTF-8啊。

**Comment by Rachel030219** [comment]
感谢反馈！由于测试设备和机型限制，这个问题可能需要时间并且不一定能修复…总之，如果取得可能的进展，我会尽快回复这个 issue。

**Comment by ckx000** [comment]
> 感谢反馈！由于测试设备和机型限制，这个问题可能需要时间并且不一定能修复…总之，如果取得可能的进展，我会尽快回复这个 issue。

十分感谢大佬的跟进。试过许多安卓版的播放器，确实只有poweramp最符合我的期望，唯一的大遗憾就是它自己不支持本地歌词，甚至它自带的或者它推荐的歌词插件都是一坨屎，唯有大佬的才是我们的希望（虽然我还没享受到 (〒︿〒)

**Comment by ckx000** [comment]
> 感谢反馈！由于测试设备和机型限制，这个问题可能需要时间并且不一定能修复…总之，如果取得可能的进展，我会尽快回复这个 issue。

。。。原因已排查出来了。。原来是某些字幕软件不遵守规范，或者说是那个根本不是lrc。。
我那个无法播放的lrc 它的时间轴是[mm:ss:xx]格式。。注意是2个冒号。。不是标准的[mm:ss.xx]格式。。我一直疏忽了这里。因为这个lrc我曾经用某个播放器正确播放出来过。。所以这个瞎眼问题一直没发现。。批量改回正确的格式就没问题了。。

**Comment by Rachel030219** [comment]
原来如此…看起来这也是一个常见的错误原因，下次更新的时候放进说明里好了

**Comment by ckx000** [comment]
> 原来如此…看起来这也是一个常见的错误原因，下次更新的时候放进说明里好了

确实 我见其他地方 例如酷安也有类似蛮多反应提示歌词不见的问题（虽然我也不见得就是同样的问题），大佬可以考虑做一个检测提示例如文件里格式有问题之类，方便用户自己知道是自己的lrc问题而不是软件的问题。同时建议不要去适配它们（不能惯着这些错误格式

**Comment by Rachel030219** [comment]
> > 原来如此…看起来这也是一个常见的错误原因，下次更新的时候放进说明里好了
> 
> 确实 我见其他地方 例如酷安也有类似蛮多反应提示歌词不见的问题（虽然我也不见得就是同样的问题），大佬可以考虑做一个检测提示例如文件里格式有问题之类，方便用户自己知道是自己的lrc问题而不是软件的问题。同时建议不要去适配它们（不能惯着这些错误格式

好的，多谢建议！
